# Generated by Django 4.0.5 on 2022-06-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calmember', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
